version: '3'

networks:
  netbusters_network:
    driver: bridge

volumes:
  pgdata:

services:
  netbusters_postgresql:
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netbusters_network

  netbusters_frontend:
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - netbusters_postgresql
    networks:
      - netbusters_network